return {
	ResearchFacility = {
		name = "ResearchFacility",
		theme = "Abandoned Research Facility",
		lighting = {
			Ambient = Color3.fromRGB(88, 96, 108),
			OutdoorAmbient = Color3.fromRGB(72, 78, 88),
			Brightness = 2,
			ClockTime = 2.5,
			FogColor = Color3.fromRGB(92, 101, 113),
			FogStart = 80,
			FogEnd = 220,
		},
		rooms = {
			{
				name = "CentralHub",
				signText = "CENTRAL HUB",
				center = Vector3.new(0, 0, 0),
				size = Vector3.new(32, 1, 26),
				floorColor = Color3.fromRGB(112, 117, 124),
				openings = {
					east = { { offset = -4, width = 6, height = 9 } },
					west = { { offset = 4, width = 6, height = 9 } },
					north = { { offset = 2, width = 7, height = 9 }, { offset = -10, width = 5, height = 4, bottom = 2 } },
					south = { { offset = -2, width = 7, height = 9 }, { offset = 10, width = 4, height = 3, bottom = 1 } },
				},
			},
			{
				name = "ServerRoom",
				signText = "SERVER ROOM",
				center = Vector3.new(28, 0, -4),
				size = Vector3.new(24, 1, 18),
				floorColor = Color3.fromRGB(100, 107, 121),
				wallColor = Color3.fromRGB(70, 78, 90),
				openings = {
					west = { { offset = 0, width = 6, height = 9 } },
					north = { { offset = -7, width = 4, height = 3, bottom = 1 } },
					south = { { offset = 7, width = 5, height = 4, bottom = 2 } },
				},
			},
			{
				name = "StorageBay",
				signText = "STORAGE BAY",
				center = Vector3.new(-28, 0, 4),
				size = Vector3.new(24, 1, 20),
				floorColor = Color3.fromRGB(118, 112, 101),
				wallColor = Color3.fromRGB(86, 80, 72),
				openings = {
					east = { { offset = 0, width = 6, height = 9 } },
					north = { { offset = -7, width = 5, height = 4, bottom = 2 } },
					south = { { offset = 7, width = 4, height = 3, bottom = 1 } },
				},
			},
			{
				name = "Laboratory",
				signText = "BIO LAB",
				center = Vector3.new(2, 0, -21),
				size = Vector3.new(22, 1, 16),
				floorColor = Color3.fromRGB(103, 119, 106),
				wallColor = Color3.fromRGB(77, 93, 82),
				openings = {
					south = { { offset = 0, width = 7, height = 9 } },
					east = { { offset = 4, width = 5, height = 4, bottom = 2 } },
					west = { { offset = -4, width = 4, height = 3, bottom = 1 } },
				},
			},
			{
				name = "GeneratorRoom",
				signText = "GENERATOR ROOM",
				center = Vector3.new(-2, 0, 21),
				size = Vector3.new(22, 1, 16),
				floorColor = Color3.fromRGB(119, 102, 99),
				wallColor = Color3.fromRGB(90, 76, 74),
				openings = {
					north = { { offset = 0, width = 7, height = 9 } },
					east = { { offset = 4, width = 4, height = 3, bottom = 1 } },
					west = { { offset = -4, width = 5, height = 4, bottom = 2 } },
				},
			},
		},
		doors = {
			{ name = "Door_Hub_Server", label = "Blast Door", position = Vector3.new(16, 0, -4), axis = "Z", width = 6, holdDuration = 2, loaderText = "Cycling blast door" },
			{ name = "Door_Hub_Storage", label = "Bulkhead", position = Vector3.new(-16, 0, 4), axis = "Z", width = 6, holdDuration = 2, loaderText = "Cycling bulkhead" },
			{ name = "Door_Hub_Lab", label = "Lab Seal", position = Vector3.new(2, 0, -13), axis = "X", width = 7, holdDuration = 2, loaderText = "Unlocking lab seal" },
			{ name = "Door_Hub_Generator", label = "Power Door", position = Vector3.new(-2, 0, 13), axis = "X", width = 7, holdDuration = 2, loaderText = "Spinning up power door" },
		},
		windows = {
			{ name = "Window_Hub_North", position = Vector3.new(-10, 0, -13), width = 5, height = 4, bottom = 2, rotation = 0 },
			{ name = "Window_Server_South", position = Vector3.new(40, 0, 5), width = 5, height = 4, bottom = 2, rotation = 90 },
			{ name = "Window_Storage_North", position = Vector3.new(-40, 0, -6), width = 5, height = 4, bottom = 2, rotation = 90 },
			{ name = "Window_Lab_East", position = Vector3.new(13, 0, -17), width = 5, height = 4, bottom = 2, rotation = 90 },
			{ name = "Window_Generator_West", position = Vector3.new(-13, 0, 17), width = 5, height = 4, bottom = 2, rotation = 90 },
		},
		vents = {
			{ name = "Vent_Hub_South", position = Vector3.new(10, 0, 13), width = 4, height = 3, bottom = 1, rotation = 0 },
			{ name = "Vent_Server_North", position = Vector3.new(21, 0, -13), width = 4, height = 3, bottom = 1, rotation = 0 },
			{ name = "Vent_Storage_South", position = Vector3.new(-21, 0, 14), width = 4, height = 3, bottom = 1, rotation = 0 },
			{ name = "Vent_Lab_West", position = Vector3.new(-9, 0, -25), width = 4, height = 3, bottom = 1, rotation = 90 },
			{ name = "Vent_Generator_East", position = Vector3.new(9, 0, 25), width = 4, height = 3, bottom = 1, rotation = 90 },
		},
		catwalks = {
			{ name = "Catwalk_Server", position = Vector3.new(28, 7.5, -4), size = Vector3.new(12, 1, 5) },
			{ name = "Catwalk_Storage", position = Vector3.new(-28, 7.5, 4), size = Vector3.new(14, 1, 5) },
		},
		slipperyFloors = {
			{ name = "CryoSpill_Lab", position = Vector3.new(6, 0.1, -18), size = Vector3.new(7, 0.2, 7) },
			{ name = "CoolantLeak_Generator", position = Vector3.new(-7, 0.1, 23), size = Vector3.new(8, 0.2, 8) },
		},
		cover = {
			{ name = "Rack_Server_A", position = Vector3.new(22, 2.5, -8), size = Vector3.new(3, 5, 2), material = Enum.Material.Metal },
			{ name = "Rack_Server_B", position = Vector3.new(34, 2.5, -2), size = Vector3.new(3, 5, 2), material = Enum.Material.Metal },
			{ name = "Crate_Storage_A", position = Vector3.new(-34, 1.5, 1), size = Vector3.new(3, 3, 3), material = Enum.Material.WoodPlanks, color = Color3.fromRGB(116, 84, 58) },
			{ name = "Crate_Storage_B", position = Vector3.new(-24, 1.5, 8), size = Vector3.new(4, 3, 4), material = Enum.Material.WoodPlanks, color = Color3.fromRGB(124, 91, 66) },
			{ name = "Counter_Lab", position = Vector3.new(-4, 1.5, -23), size = Vector3.new(6, 3, 2), material = Enum.Material.Metal },
			{ name = "Turbine_Generator", position = Vector3.new(2, 2.5, 23), size = Vector3.new(5, 5, 5), material = Enum.Material.Metal },
			{ name = "Hub_Console", position = Vector3.new(0, 1.5, -3), size = Vector3.new(5, 3, 2), material = Enum.Material.Metal },
		},
		tasks = {
			{ name = "Hack_ServerRack", type = "ComputerHack", label = "Server Rack", position = Vector3.new(33, 0, -8), holdDuration = 3, loaderText = "Injecting terminal exploit" },
			{ name = "Hack_BioTerminal", type = "ComputerHack", label = "Bio Terminal", position = Vector3.new(8, 0, -24), holdDuration = 3, loaderText = "Decrypting lab archives" },
			{ name = "Hack_PowerConsole", type = "ComputerHack", label = "Power Console", position = Vector3.new(-8, 0, 18), holdDuration = 3, loaderText = "Rerouting generator output" },
			{ name = "Valve_CoolantLoop", type = "ValveTurn", position = Vector3.new(3, 0, 25), turnsRequired = 3 },
			{ name = "Valve_StoragePressure", type = "ValveTurn", position = Vector3.new(-35, 0, -2), turnsRequired = 3 },
			{ name = "Panel_SecurityOverride", type = "PanelPuzzle", position = Vector3.new(10, 0, 6), sequence = { 1, 3, 2 } },
			{ name = "Panel_LabAirlock", type = "PanelPuzzle", position = Vector3.new(-7, 0, -18), sequence = { 2, 1, 3 } },
		},
		spawns = {
			{ name = "MainSpawn", position = Vector3.new(0, 2, 0), size = Vector3.new(10, 1, 10) },
		},
	},
}